version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: WebApplicationConsumer/Dockerfile
    restart: always
    deploy:
      replicas: 4

  producer-1:
    build:
      context: .
      dockerfile: WebApplicationProducer/Dockerfile
    ports:
      - "8082:8080"

  producer-2:
    build:
      context: .
      dockerfile: WebApplicationProducer/Dockerfile
    ports:
      - "8083:8080"
