version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: WebApplicationConsumer/Dockerfile
    restart: always
    deploy:
      replicas: 10

  producer:
    build:
      context: .
      dockerfile: WebApplicationProducer/Dockerfile
    ports:
      - "8085:8080"
    restart: always