version: '3.8'

services:
  consumer:
    build:
      context: ./WebApplicationConsumer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  producer:
    build:
      context: ./WebApplicationProducer
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
      - "8083:8081"
