version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: WebApplicationConsumer/Dockerfile
    restart: always

  producer:
    build:
      context: .
      dockerfile: WebApplicationProducer/Dockerfile
    ports:
      - "8082:8082"
    restart: always
