version: '3.8'

services:
  consumer:
    build:
      dockerfile: WebApplicationConsumer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  producer:
    build:
      dockerfile: WebApplicationProducer/Dockerfile
    ports:
      - "8082:8080"
      - "8083:8081"
